### ISSUE TITLE
"Please set the TOKEN environment variable." when it's set

### ISSUE THREAD

**Issue by MaxGhenis** [jeffreytse/jekyll-deploy-action#9] opened 2021-03-11 21:57 UTC
In https://github.com/UBICenter/ubicenter.org/pull/63 I'm trying to test my deployment using instructions from #5. I've set a token per the instructions here, and also tried regenerating a new PAT to make sure, but I'm still getting the error `Please set the TOKEN environment variable.`

![image](https://user-images.githubusercontent.com/6076111/110860834-2135f900-8272-11eb-879e-0263cc77f5e4.png)

Am I doing something wrong?

Here's the latest check: https://github.com/UBICenter/ubicenter.org/pull/63/checks?check_run_id=2090117003#step:5:10
```
Run jeffreytse/jekyll-deploy-action@v0.2.0
  with:
    provider: github
    branch: test
    jekyll_src: ./
    jekyll_cfg: _config.yml
    bundler_ver: >=0
/usr/bin/docker run --name e4becc7f4f6ad24da1b18df98d2f857e72_944ae4 --label 5588e4 --workdir /github/workspace --rm -e INPUT_PROVIDER -e INPUT_TOKEN -e INPUT_REPOSITORY -e INPUT_BRANCH -e INPUT_JEKYLL_SRC -e INPUT_JEKYLL_CFG -e INPUT_JEKYLL_BASEURL -e INPUT_BUNDLER_VER -e INPUT_CNAME -e INPUT_ACTOR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ubicenter.org/ubicenter.org":"/github/workspace" 5588e4:becc7f4f6ad24da1b18df98d2f857e72
Starting the Jekyll Deploy Action
Please set the TOKEN environment variable.
```

**Comment by jeffreytse** [comment] 2021-03-12 02:22
Hi @MaxGhenis ,  I want  to  confirm that if this action is working well in you repository (https://github.com/MaxGhenis/ubicenter.org/tree/action)? Or the same problem?

**Comment by MaxGhenis** [comment] 2021-03-12 06:43
Ohh is this because I only have `GH_TOKEN` on the main repo (UBICenter/ubicenter.org), rather than my fork from which I'm PRing (MaxGhenis/ubicenter.org)? It's worked upon merging, e.g. in https://github.com/UBICenter/ubicenter.org/actions/runs/633636810.

If that's the cause, is there a way to use the `GH_TOKEN` across forks? Otherwise each contributor would need to set up a token right?

**Comment by jeffreytse** [comment] 2021-03-12 06:50
Hi @MaxGhenis , you are right, each contirbutor would need to set up a token and do the test in its fork repo, after merging to the main brach of the repo (UBICenter/ubicenter.org), the action will use the `GH_TOKEN` in the repo, we can not use the `GH_TOKEN` across forks because of the permission issue.

**Comment by MaxGhenis** [comment] 2021-03-12 07:07
OK, I added a `GH_TOKEN` secret to the MaxGhenis/ubicenter.org repo, but still getting the same error: https://github.com/UBICenter/ubicenter.org/pull/63/checks?check_run_id=2092885527

**Comment by jeffreytse** [comment] 2021-03-12 07:18
Hi @MaxGhenis

Could you add a `GH_TOKEN` secret to the `MaxGhenis/ubicenter.org` repo and then rerun the action in `MaxGhenis/ubicenter.org` again? After completing them please tell me the result.

Thanks and regards

**Comment by MaxGhenis** [comment] 2021-03-12 07:23
I can't create another `GH_TOKEN` secret in `MaxGhenis/ubicenter.org`. Would you like me to regenerate it again, or just re-run the action?

**Comment by jeffreytse** [comment] 2021-03-12 07:25
Hi @MaxGhenis , yes, to regenerate it again, and just re-run the action.

**Comment by MaxGhenis** [comment] 2021-03-12 07:29
Same error: https://github.com/UBICenter/ubicenter.org/pull/63/checks?check_run_id=2093007354

**Comment by jeffreytse** [comment] 2021-03-12 07:35
Hi @MaxGhenis ,
I think you should remove this condition and re-run the action in your fork's repos (i.e. https://github.com/MaxGhenis/ubicenter.org) and see the result.

![image](https://user-images.githubusercontent.com/9413601/110907501-76443e80-8348-11eb-8311-5a76f764afa4.png)

**Comment by MaxGhenis** [comment] 2021-03-12 17:26
No change: https://github.com/UBICenter/ubicenter.org/pull/63/checks?check_run_id=2097162809

**Comment by jeffreytse** [comment] 2021-03-13 02:15
Hi @MaxGhenis , maybe the problem is that your action is not in the master branch, could you have a test in the master branch?

**Comment by MaxGhenis** [comment] 2021-03-13 06:23
It ran successfully when merging, i.e. from `master`: https://github.com/UBICenter/ubicenter.org/actions/runs/648414168

So I guess this might be more of an issue around testing (#5). Is there a way to test the action in a PR from a non-master branch of a personal fork? There's nothing about `master` in the .yml so I'm a bit confused, but this is my normal workflow.

**Comment by jeffreytse** [comment] 2021-03-13 06:53
Hi @MaxGhenis 

Github Actions did the right thing by making the `$GITHUB_TOKEN` read-only and secrets unavailable for forks for security reasons, but this can be a big limitation. Short of making a key publically available, parts of the CI process would just have to be disabled.

So I think you can do as below:

1. Create a new repository and add it as a new remote upstream repository that will be synced.

```shell
$ git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
```

2. Verify the new upstream repository you've specified for your fork.
```shell
$ git remote -v
> origin    https://github.com/YOUR_USERNAME/YOUR_FORK.git (fetch)
> origin    https://github.com/YOUR_USERNAME/YOUR_FORK.git (push)
> upstream  https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git (fetch)
> upstream  https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git (push)
```

3. You push and test it with this new upstream repository.
4. After the test passed, you sync it to the upstream  fork's repository.

Thanks and regards

**Comment by jeffreytse** [comment] 2021-03-19 07:04
Hi @MaxGhenis  , Could we close this issue now? : )

**Closed** 2021-03-20 04:04 UTC
Labels: question
